"""添加todo列表

Revision ID: 194ba4473207
Revises: b027ad948f79
Create Date: 2019-05-22 09:55:48.130346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194ba4473207'
down_revision = 'b027ad948f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_timestamp'), 'item', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_timestamp'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
